package me.mudkip.moememos.ui.theme

import androidx.compose.ui.graphics.Color

val SpaceBlue = Color(0xFF2F78ED)
val SpaceBlueDark = Color(0xFF174EA6)

val md_theme_light_primary = SpaceBlueDark
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD9E6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A41)
val md_theme_light_secondary = Color(0xFF535F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7E3F8)
val md_theme_light_onSecondaryContainer = Color(0xFF101C2B)
val md_theme_light_tertiary = Color(0xFF3B6471)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBFE9F8)
val md_theme_light_onTertiaryContainer = Color(0xFF001F27)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6F7FB)
val md_theme_light_onBackground = Color(0xFF191C20)
val md_theme_light_surface = Color(0xFFFBF8FF)
val md_theme_light_onSurface = Color(0xFF191C20)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inverseSurface = Color(0xFF2E3035)
val md_theme_light_inversePrimary = Color(0xFFADC6FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = SpaceBlueDark

val md_theme_dark_primary = Color(0xFFADC6FF)
val md_theme_dark_onPrimary = Color(0xFF002E69)
val md_theme_dark_primaryContainer = Color(0xFF004494)
val md_theme_dark_onPrimaryContainer = Color(0xFFD9E6FF)
val md_theme_dark_secondary = Color(0xFFBBC7DB)
val md_theme_dark_onSecondary = Color(0xFF253141)
val md_theme_dark_secondaryContainer = Color(0xFF3B4858)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7E3F8)
val md_theme_dark_tertiary = Color(0xFFA3CDDC)
val md_theme_dark_onTertiary = Color(0xFF033541)
val md_theme_dark_tertiaryContainer = Color(0xFF224C58)
val md_theme_dark_onTertiaryContainer = Color(0xFFBFE9F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF111318)
val md_theme_dark_onBackground = Color(0xFFE2E2E9)
val md_theme_dark_surface = Color(0xFF111318)
val md_theme_dark_onSurface = Color(0xFFE2E2E9)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6CF)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF111318)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E9)
val md_theme_dark_inversePrimary = SpaceBlueDark
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFADC6FF)


val seed = SpaceBlue

// Material Color Utilities 0.3.0 CorePalette tones generated from the existing green seed (0xFF006D42).
val md_theme_light_surfaceDim = Color(0xFFD9DBD6)
val md_theme_light_surfaceBright = Color(0xFFF8FAF5)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF2F4EF)
val md_theme_light_surfaceContainer = Color(0xFFEDEEEA)
val md_theme_light_surfaceContainerHigh = Color(0xFFE7E9E4)
val md_theme_light_surfaceContainerHighest = Color(0xFFE1E3DE)
val md_theme_light_outlineVariant = Color(0xFFC0C9C0)
val md_theme_dark_surfaceDim = Color(0xFF111412)
val md_theme_dark_surfaceBright = Color(0xFF373A37)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0C0F0D)
val md_theme_dark_surfaceContainerLow = Color(0xFF191C1A)
val md_theme_dark_surfaceContainer = Color(0xFF1D201E)
val md_theme_dark_surfaceContainerHigh = Color(0xFF282B28)
val md_theme_dark_surfaceContainerHighest = Color(0xFF323633)
val md_theme_dark_outlineVariant = Color(0xFF404942)

// Fixed accent roles use the same tones in light and dark themes.
val md_theme_primaryFixed = Color(0xFFD9E6FF)
val md_theme_primaryFixedDim = Color(0xFFADC6FF)
val md_theme_onPrimaryFixed = Color(0xFF001A41)
val md_theme_onPrimaryFixedVariant = Color(0xFF004494)
val md_theme_secondaryFixed = Color(0xFFD7E3F8)
val md_theme_secondaryFixedDim = Color(0xFFBBC7DB)
val md_theme_onSecondaryFixed = Color(0xFF101C2B)
val md_theme_onSecondaryFixedVariant = Color(0xFF3B4858)
val md_theme_tertiaryFixed = Color(0xFFBFE9F8)
val md_theme_tertiaryFixedDim = Color(0xFFA3CDDC)
val md_theme_onTertiaryFixed = Color(0xFF001F27)
val md_theme_onTertiaryFixedVariant = Color(0xFF224C58)
